factory=('F1' 'F2' 'F3' 'F4' 'F5' 'F6' 'F7' 'F8' 'F8B' 'FT6' 'L1' 'L2' 'L3' 'L4' 'L5' 'L6' 'L7' 'L8' 'LT6' 'LU' 'T1' 'T2' 'T3' 'T4' 'T5' 'T6' 'T7' 'T8' 'T8B' 'TT6')
F1=('PDATA_EDA.MEA_EDC_F1' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_F1' 'PDATA_QIS.DDPR_CALC_RES_F1' 'PDATA_QIS.DPPR_META_F1' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_F1' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_F1' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_F1' 'PMART_EDA.BI_SUM_SUM_F1')
F2=('PDATA_EDA.MEA_EDC_F2' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_F2' 'PDATA_QIS.DDPR_CALC_RES_F2' 'PDATA_QIS.DPPR_META_F2' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_F2' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_F2' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_F2' 'PMART_EDA.BI_SUM_SUM_F2')
F3=('PDATA_EDA.MEA_EDC_F3' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_F3' 'PDATA_QIS.DDPR_CALC_RES_F3' 'PDATA_QIS.DPPR_META_F3' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_F3' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_F3' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_F3' 'PMART_EDA.BI_SUM_SUM_F3')
F4=('PDATA_EDA.MEA_EDC_F4' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_F4' 'PDATA_QIS.DDPR_CALC_RES_F4' 'PDATA_QIS.DPPR_META_F4' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_F4' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_F4' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_F4' 'PMART_EDA.BI_SUM_SUM_F4')
F5=('PDATA_EDA.MEA_EDC_F5' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_F5' 'PDATA_QIS.DDPR_CALC_RES_F5' 'PDATA_QIS.DPPR_META_F5' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_F5' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_F5' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_F5' 'PMART_EDA.BI_SUM_SUM_F5')
F6=('PDATA_EDA.MEA_EDC_F6' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_F6' 'PDATA_QIS.DDPR_CALC_RES_F6' 'PDATA_QIS.DPPR_META_F6' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_F6' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_F6' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_F6' 'PMART_EDA.BI_SUM_SUM_F6')
F7=('PDATA_EDA.MEA_EDC_F7' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_F7' 'PDATA_QIS.DDPR_CALC_RES_F7' 'PDATA_QIS.DPPR_META_F7' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_F7' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_F7' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_F7' 'PMART_EDA.BI_SUM_SUM_F7')
F8=('PDATA_EDA.MEA_EDC_F8' 'PDATA_EDA.MEA_SPC_F8' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_DCI_F8' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_F8' 'PDATA_QIS.DDPR_CALC_RES_F8' 'PDATA_QIS.DPPR_META_F8' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_F8' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_F8' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_F8' 'PMART_EDA.BI_SUM_SUM_F8' 'PMART_EDA.MEA_EDC_ISPEC_F8')
F8B=('PDATA_EDA.MEA_EDC_F8B' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_F8B' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_F8B' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_F8B' 'PMART_EDA.BI_SUM_SUM_F8B')
FT6=('PDATA_EDA.MEA_EDC_FT6' 'PDATA_QIS.DDPR_CALC_RES_FT6' 'PDATA_QIS.DPPR_META_FT6' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_FT6' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_FT6' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_FT6' 'PMART_EDA.BI_SUM_SUM_FT6')
L1=('PDATA_EDA.MEA_EDC_L1' 'PDATA_QIS.DDPR_CALC_RES_L1' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_L1' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_L1' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_L1' 'PMART_EDA.BI_SUM_SUM_L1')
L2=('PDATA_EDA.MEA_EDC_L2' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_L2' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_L2' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_L2' 'PMART_EDA.BI_SUM_SUM_L2')
L3=('PDATA_EDA.MEA_EDC_L3' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_L3' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_L3' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_L3' 'PMART_EDA.BI_SUM_SUM_L3')
L4=('PDATA_EDA.MEA_EDC_L4' 'PDATA_QIS.DPPR_META_L4' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_L4' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_L4' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_L4' 'PMART_EDA.BI_SUM_SUM_L4')
L5=('PDATA_EDA.MEA_EDC_L5' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_L5' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_L5' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_L5' 'PMART_EDA.BI_SUM_SUM_L5')
L6=('PDATA_EDA.MEA_EDC_L6' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_L6' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_L6' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_L6' 'PMART_EDA.BI_SUM_SUM_L6')
L7=('PDATA_EDA.MEA_EDC_L7' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_L7' 'PDATA_QIS.DDPR_CALC_RES_L7' 'PDATA_QIS.DPPR_META_L7' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_L7' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_L7' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_L7' 'PMART_EDA.BI_SUM_SUM_L7')
L8=('PDATA_EDA.MEA_EDC_L8' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_DCI_L8' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_L8' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_L8' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_L8' 'PMART_EDA.BI_SUM_SUM_L8')
LT6=('PDATA_EDA.MEA_EDC_LT6' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_LT6' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_LT6' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_LT6' 'PMART_EDA.BI_SUM_SUM_LT6')
LU=('PDATA_EDA.MEA_EDC_LU' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_LU' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_LU' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_LU' 'PMART_EDA.BI_SUM_SUM_LU')
T1=('PDATA_EDA.MEA_EDC_T1' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_T1' 'PDATA_QIS.DDPR_CALC_RES_T1' 'PDATA_QIS.DPPR_META_T1' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_T1' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_T1' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_T1' 'PMART_EDA.BI_SUM_SUM_T1')
T2=('PDATA_EDA.MEA_EDC_T2' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_T2' 'PDATA_QIS.DDPR_CALC_RES_T2' 'PDATA_QIS.DPPR_META_T2' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_T2' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_T2' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_T2' 'PMART_EDA.BI_SUM_SUM_T2')
T3=('PDATA_EDA.MEA_EDC_T3' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_T3' 'PDATA_QIS.DDPR_CALC_RES_T3' 'PDATA_QIS.DPPR_META_T3' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_T3' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_T3' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_T3' 'PMART_EDA.BI_SUM_SUM_T3')
T4=('PDATA_EDA.MEA_EDC_T4' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_T4' 'PDATA_QIS.DDPR_CALC_RES_T4' 'PDATA_QIS.DPPR_META_T4' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_T4' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_T4' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_T4' 'PMART_EDA.BI_SUM_SUM_T4')
T5=('PDATA_EDA.MEA_EDC_T5' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_T5' 'PDATA_QIS.DDPR_CALC_RES_T5' 'PDATA_QIS.DPPR_META_T5' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_T5' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_T5' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_T5' 'PMART_EDA.BI_SUM_SUM_T5')
T6=('PDATA_EDA.MEA_EDC_T6' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_T6' 'PDATA_QIS.DDPR_CALC_RES_T6' 'PDATA_QIS.DPPR_META_T6' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_T6' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_T6' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_T6' 'PMART_EDA.BI_SUM_SUM_T6')
T7=('PDATA_EDA.MEA_EDC_T7' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_T7' 'PDATA_QIS.DDPR_CALC_RES_T7' 'PDATA_QIS.DPPR_META_T7' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_T7' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_T7' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_T7' 'PMART_EDA.BI_SUM_SUM_T7')
T8=('PDATA_EDA.MEA_EDC_T8' 'PDATA_EDA.MEA_SPC_T8' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_DCI_T8' 'PDATA_EDA.PDN_PNL_DFCT_RTQCS_T8' 'PDATA_QIS.DCIC_HIS_T8' 'PDATA_QIS.DCIC_META_T8' 'PDATA_QIS.DDPR_CALC_RES_T8' 'PDATA_QIS.DPPR_META_T8' 'PMART_EDA.BI_MEA_DCI_RTQCS_SUM_T8' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_T8' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_T8' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_T8' 'PMART_EDA.BI_SUM_SUM_T8')
T8B=('PDATA_EDA.MEA_EDC_CHK_HIS_T8B' 'PDATA_EDA.MEA_EDC_T8B' 'PDATA_QIS.DDPR_CALC_RES_T8B' 'PDATA_QIS.DPPR_META_T8B' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_T8B' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_T8B' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_T8B' 'PMART_EDA.BI_SUM_SUM_T8B')
TT6=('PDATA_EDA.MEA_EDC_TT6' 'PMART_EDA.BI_MEA_EDC_ISPEC_CHK_TT6' 'PMART_EDA.BI_MEA_EDC_ISPEC_DEFINE_EXPA_TT6' 'PMART_EDA.BI_MEA_EDC_ISPEC_SUM_TT6' 'PMART_EDA.BI_SUM_SUM_TT6')

function decide(){
    string=$1
    factory=$2
    if [ $string == $factory ]
    then
        echo $factory
    fi
}

for f in ${factory[*]}
do
    decide $1 $f
done

echo $(decide $1 F1)
echo $1
# echo ${F1[*]}
# factory=$1
# echo ${factory[*]}
# for t in ${factory[*]}
# do
#     echo $t
# done